### ISSUE TITLE
The child node "database" at path "bm_backup_manager" must be configured. - Symfony 4

### ISSUE THREAD

**Issue by elvismdev** [backup-manager/symfony#34]
Hi, is this bundle currently compatible with Symfony 4? Trying to install it but getting this error instead.

![selection_137](https://user-images.githubusercontent.com/3847077/36888194-40e6dda4-1da9-11e8-8d82-766b3bf359cb.jpg)

**Comment by Nyholm** [comment]
Hey. Just add some configuration and you will be good to go. 

I'll make sure to fix this error. Thank you for reporting this.

**Comment by elvismdev** [comment]
@Nyholm Thanks for the quick response. So I did and placed a config file at `config/packages/bm_backup_manager.yaml` with the following values.

```
bm_backup_manager:
  database:
    development:
      type: mysql
      host: localhost
      port: 3306
      user: root
      pass: root
      database: test
    production:
      type: mysql
      host: localhost
      port: 3306
      user: root
      pass: root
      database: test
  storage:
    local:
      type: Local
      root: /path/to/working/directory
```
The bundle installation passed the before mentioned error, but after I got blocked with another different one. Hope this helps to give you context for a fix for SF4.

![selection_138](https://user-images.githubusercontent.com/3847077/36889357-77d0cb22-1dae-11e8-912b-2cbe51f82335.jpg)
