### ISSUE TITLE
Fatal error: Environment variables "DATABASE_URL" are never used. Please, check your container's configuration.

### ISSUE THREAD

**Issue by elvismdev** [backup-manager/symfony#42]
I'm currently testing #39. I've updated the config for this bundle at `config/packages/bm_backup_manager.yaml` to look like this:

```
bm_backup_manager:
    database:
        development:
            dsn: '%env(DATABASE_URL)%'
        production:
            dsn: '%env(DATABASE_URL)%'
    storage:
        local:
            type: Local
            root: /home/elvismdev/WWW/my_sf4_app/_db_backup
```

Now, when I run the command to fire the DB backup:

```
php bin/console backup-manager:backup development local -c gzip
```

It throws this fatal error:
![selection_139](https://user-images.githubusercontent.com/3847077/36953733-df33f58a-1fd1-11e8-9663-d24c60f3f111.jpg)

On other hand, if instead using `%env(DATABASE_URL)%` for the DSN value I place directly in the yaml file my DB details like `mysql://root:root@127.0.0.1:3306/test`, it does works and backups the DB successfully as expected.

If that helps, I found a similar issue/error reported here https://github.com/symfony/symfony/issues/23520
