### ISSUE TITLE
Could not find configuration for connection local

### ISSUE THREAD

**Issue by nicotec** [backup-manager/symfony#66]
Hello :),

```
parameters:
    bdd.backup.dir: "/var/www/html/backup"

bm_backup_manager:
    database:
        db:
            dsn: '%env(resolve:DATABASE_URL)%'
    storage:
#        local:
#            type: Local
#            root: "%bdd.backup.dir%"
        local_backup:
            type: Local
            root: "%bdd.backup.dir%"
        local_tmp:
            type: Local
            root: "/tmp"
```

```
php bin/console backup-manager:restore db local_tmp /ed_611712.sql.gz -c gzip
```

Multiple local folders cannot be configured. It tries to take the "local" configuration :
```
Could not find configuration for connection local
```
