### ISSUE TITLE
Bundle fails on dsn define

### ISSUE THREAD

**Issue by jfuentesb** [backup-manager/symfony#75]
mysql://user:pass@server:3306/database

And show me:
mysqldump: Got error: 1049: "Unknown database '/database'" when selecting the database. I think that this take the '/' too.

**Comment by frvaillant** [comment]
I got the same issue. There is also a problem when database password contains "@"

**Comment by lhpalacio** [comment]
@jfuentesb and @frvaillant nice catch! for now is better to avoid DSN config.

A workaround is set database connection config like this:
```
bm_backup_manager:
    database:
        development:
            type: mysql
            host: localhost
            port: 3306
            user: root
            pass: pass@word
            database: test
```

@Nyholm A `parse_url` function is not enough to parser the DSN config?
